var ccb_resources = [
    {type:'sound', src:"sounds/MIAO1.mp3"},
    {type:'image', src:"sprites/cat/cat_punched_notified.png"},
    {type:'image', src:"sprites/buttons/button_pressed.png"},
    {type:'image', src:"ccbResources/ccbDefaultImages.png"},
    {type:'ccbi', src:"PunchScene.ccbi"},
    {type:'image', src:"clickme.png"},
    {type:'ccbi', src:"MainScene.ccbi"},
    {type:'image', src:"sprites/punch_point/punch_point.png"},
    {type:'image', src:"clickme-down.png"},
    {type:'image', src:"sprites/particles/sprite_heart.png"},
    {type:'image', src:"ccbResources/ccbParticleSmoke.png"},
    {type:'image', src:"sprites/cat/cat_normal.png"},
    {type:'sound', src:"sounds/CAT_ROCK_VER.mp3"},
    {type:'image', src:"ccbResources/ccbParticleSnow.png"},
    {type:'image', src:"sprites/buttons/button_normal.png"},
    {type:'sound', src:"sounds/CAT_FIGHT_BG.mp3"},
    {type:'sound', src:"sounds/CAT_OP_BG.mp3"},
    {type:'image', src:"sprites/cat/cat_punched.png"},
    {type:'image', src:"ccbResources/ccbParticleStars.png"},
    {type:'image', src:"ccbResources/ccbParticleFire.png"},
    {type:'image', src:"sprites/cat/cat_normal_notified.png"},
    {type:'ccbi', src:"CCSpriteButton.ccbi"},
    {type:'plist', src:"ccbResources/ccbDefaultImages.plist"},
];
